language: ruby
before_install:
- gem install bundler:2.0.2
rvm:
- 2.6.3
script: bundle exec middleman build
branches:
  only:
  - master
addons:
  ssh_known_hosts: skua.jamesmead.org
before_deploy:
- openssl aes-256-cbc -K $encrypted_2010d656fd11_key -iv $encrypted_2010d656fd11_iv -in travisci_rsa.enc -out /tmp/travisci_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/travisci_rsa
- ssh-add /tmp/travisci_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -avz build/ travisci@skua.jamesmead.org:/var/www/jamesmead.org
  on:
    branch: master
after_deploy:
- kill $SSH_AGENT_PID
- rm /tmp/travisci_rsa
